# Generated by Django 3.2 on 2023-09-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('History', 'History')], default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='estimated_time',
            field=models.DurationField(blank=True, help_text='Estimated time for the lesson (in hours:minutes:seconds)', null=True),
        ),
    ]
