# Generated by Django 3.2 on 2023-09-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20230918_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='attachments',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned',
            field=models.CharField(choices=[('Barry', 'Barry'), ('John', 'Sarah'), ('Rachel', 'Rachel'), ('Sue', 'Sue')], default='Sue', max_length=20),
        ),
    ]
