# Generated by Django 3.2 on 2023-09-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='video_url',
        ),
    ]
